import os
from dotenv import load_dotenv

load_dotenv()

CLAUDE_API_KEY = os.getenv("ANTHROPIC_API_KEY")
CLAUDE_MODEL = "claude-sonnet-4-20250514"
CLAUDE_MAX_TOKENS = 4096

BOOTSTRAP_PEERS = [p for p in os.getenv("HIVEMIND_BOOTSTRAP_PEERS", "").split(",") if p]
DHT_PORT = int(os.getenv("DHT_PORT", "12345"))

TASK_TIMEOUT = 120
RESULT_COLLECTION_POLL_INTERVAL = 1

DEFAULT_COMMIT_MESSAGE = "Auto-generated by DELLM distributed coding platform"
