import os
import logging
from git import Repo
from shared.models import Task, Result

logger = logging.getLogger(__name__)


def _topological_sort(tasks: list[Task]) -> list[Task]:
    """Sort tasks by dependencies."""
    task_map = {t.id: t for t in tasks}
    visited = set()
    order = []

    def visit(tid):
        if tid in visited:
            return
        visited.add(tid)
        task = task_map.get(tid)
        if task:
            for dep in task.dependencies:
                visit(dep)
            order.append(task)

    for t in tasks:
        visit(t.id)
    return order


def merge_results(tasks: list[Task], results: dict[int, Result], repo_path: str) -> str:
    """Write generated code to files in a git repo and commit."""
    # Init or open repo
    if os.path.exists(os.path.join(repo_path, ".git")):
        repo = Repo(repo_path)
    else:
        os.makedirs(repo_path, exist_ok=True)
        repo = Repo.init(repo_path)

    sorted_tasks = _topological_sort(tasks)
    files_written = []

    for task in sorted_tasks:
        if task.id not in results:
            logger.warning(f"No result for task {task.id}, skipping")
            continue

        result = results[task.id]
        dir_path = os.path.join(repo_path, task.directory)
        os.makedirs(dir_path, exist_ok=True)

        file_path = os.path.join(dir_path, task.file)
        with open(file_path, "w") as f:
            f.write(result.code)

        rel_path = os.path.relpath(file_path, repo_path)
        repo.index.add([rel_path])
        files_written.append(rel_path)
        logger.info(f"Wrote {rel_path}")

    if files_written:
        commit = repo.index.commit("Auto-generated by DELLM distributed coding platform")
        logger.info(f"Committed: {commit.hexsha}")
        return commit.hexsha

    logger.warning("No files written, no commit made")
    return ""
